/* soapServer.c
   Generated by gSOAP 2.8.7 from dollySoap.h

Copyright(C) 2000-2011, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) soapServer.c ver 2.8.7 2013-08-14 16:48:54 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap *soap)
{
#ifndef WITH_FASTCGI
	unsigned int k = soap->max_keep_alive;
#endif
	do
	{
#ifndef WITH_FASTCGI
		if (soap->max_keep_alive > 0 && !--k)
			soap->keep_alive = 0;
#endif
		if (soap_begin_serve(soap))
		{	if (soap->error >= SOAP_STOP)
				continue;
			return soap->error;
		}
		if (soap_serve_request(soap) || (soap->fserveloop && soap->fserveloop(soap)))
		{
#ifdef WITH_FASTCGI
			soap_send_fault(soap);
#else
			return soap_send_fault(soap);
#endif
		}

#ifdef WITH_FASTCGI
		soap_destroy(soap);
		soap_end(soap);
	} while (1);
#else
	} while (soap->keep_alive);
#endif
	return SOAP_OK;
}

#ifndef WITH_NOSERVEREQUEST
SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap *soap)
{
	soap_peek_element(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:sendCmd"))
		return soap_serve___ns1__sendCmd(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:getConfig"))
		return soap_serve___ns1__getConfig(soap);
	return soap->error = SOAP_NO_METHOD;
}
#endif

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__sendCmd(struct soap *soap)
{	struct __ns1__sendCmd soap_tmp___ns1__sendCmd;
	struct _ns1__sendCmdResponse ns1__sendCmdResponse;
	soap_default__ns1__sendCmdResponse(soap, &ns1__sendCmdResponse);
	soap_default___ns1__sendCmd(soap, &soap_tmp___ns1__sendCmd);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__sendCmd(soap, &soap_tmp___ns1__sendCmd, "-ns1:sendCmd", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__sendCmd(soap, soap_tmp___ns1__sendCmd.ns1__sendCmd, &ns1__sendCmdResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__ns1__sendCmdResponse(soap, &ns1__sendCmdResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__ns1__sendCmdResponse(soap, &ns1__sendCmdResponse, "ns1:sendCmdResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__ns1__sendCmdResponse(soap, &ns1__sendCmdResponse, "ns1:sendCmdResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__getConfig(struct soap *soap)
{	struct __ns1__getConfig soap_tmp___ns1__getConfig;
	struct _ns1__getConfigResponse ns1__getConfigResponse;
	soap_default__ns1__getConfigResponse(soap, &ns1__getConfigResponse);
	soap_default___ns1__getConfig(soap, &soap_tmp___ns1__getConfig);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__getConfig(soap, &soap_tmp___ns1__getConfig, "-ns1:getConfig", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__getConfig(soap, soap_tmp___ns1__getConfig.ns1__getConfig, &ns1__getConfigResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__ns1__getConfigResponse(soap, &ns1__getConfigResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__ns1__getConfigResponse(soap, &ns1__getConfigResponse, "ns1:getConfigResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__ns1__getConfigResponse(soap, &ns1__getConfigResponse, "ns1:getConfigResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapServer.c */
