/* soapStub.h
   Generated by gSOAP 2.8.7 from dollySoap.h

Copyright(C) 2000-2011, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapStub_H
#define soapStub_H
#include "stdsoap2.h"
#if GSOAP_H_VERSION != 20807
# error "GSOAP VERSION MISMATCH IN GENERATED CODE: PLEASE REINSTALL PACKAGE"
#endif

#ifdef __cplusplus
extern "C" {
#endif

/******************************************************************************\
 *                                                                            *
 * Enumerations                                                               *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes and Structs                                                        *
 *                                                                            *
\******************************************************************************/


#if 0 /* volatile type: do not declare here, declared elsewhere */

#endif

#ifndef SOAP_TYPE__ns1__sendCmd
#define SOAP_TYPE__ns1__sendCmd (7)
/* ns1:sendCmd */
struct _ns1__sendCmd
{
	int cmd;	/* required element of type xsd:int */
	int p1;	/* required element of type xsd:int */
	int p2;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE__ns1__sendCmdResponse
#define SOAP_TYPE__ns1__sendCmdResponse (8)
/* ns1:sendCmdResponse */
struct _ns1__sendCmdResponse
{
	int retval;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE__ns1__getConfig
#define SOAP_TYPE__ns1__getConfig (9)
/* ns1:getConfig */
struct _ns1__getConfig
{
	int p1;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE__ns1__getConfigResponse
#define SOAP_TYPE__ns1__getConfigResponse (10)
/* ns1:getConfigResponse */
struct _ns1__getConfigResponse
{
	char *out;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE___ns1__sendCmd
#define SOAP_TYPE___ns1__sendCmd (14)
/* Operation wrapper: */
struct __ns1__sendCmd
{
	struct _ns1__sendCmd *ns1__sendCmd;	/* optional element of type ns1:sendCmd */
};
#endif

#ifndef SOAP_TYPE___ns1__getConfig
#define SOAP_TYPE___ns1__getConfig (18)
/* Operation wrapper: */
struct __ns1__getConfig
{
	struct _ns1__getConfig *ns1__getConfig;	/* optional element of type ns1:getConfig */
};
#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (19)
/* SOAP Header: */
struct SOAP_ENV__Header
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (20)
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
	char *SOAP_ENV__Value;	/* optional element of type xsd:QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (22)
/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
	char *__any;
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (25)
/* SOAP-ENV:Reason */
struct SOAP_ENV__Reason
{
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (26)
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
	char *faultcode;	/* optional element of type xsd:QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
};
#endif

#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif

#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (6)
typedef char *_XML;
#endif


/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Server-Side Operations                                                     *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 __ns1__sendCmd(struct soap*, struct _ns1__sendCmd *ns1__sendCmd, struct _ns1__sendCmdResponse *ns1__sendCmdResponse);

SOAP_FMAC5 int SOAP_FMAC6 __ns1__getConfig(struct soap*, struct _ns1__getConfig *ns1__getConfig, struct _ns1__getConfigResponse *ns1__getConfigResponse);

/******************************************************************************\
 *                                                                            *
 * Server-Side Skeletons to Invoke Service Operations                         *
 *                                                                            *
\******************************************************************************/

SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__sendCmd(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__getConfig(struct soap*);

/******************************************************************************\
 *                                                                            *
 * Client-Side Call Stubs                                                     *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__sendCmd(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__sendCmd *ns1__sendCmd, struct _ns1__sendCmdResponse *ns1__sendCmdResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getConfig(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getConfig *ns1__getConfig, struct _ns1__getConfigResponse *ns1__getConfigResponse);

#ifdef __cplusplus
}
#endif

#endif

/* End of soapStub.h */
